name: Fix dead code with deadnix
on:
  push:
    paths:
      - "**.nix"
  workflow_dispatch:

jobs:
  deadnix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Set Up Nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run deadnix check
        uses: workflow/nix-shell-action@main
        continue-on-error: true
        with:
          packages: deadnix
          script: |
            deadnix
      - name: Run deadnix fix
        uses: workflow/nix-shell-action@main
        with:
          packages: deadnix
          script: |
            deadnix -e
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix dead code using deadnix"
