name: Lint with statix
on:
  push:
    paths:
      - "**.nix"
  workflow_dispatch:

jobs:
  statix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Set Up Nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run statix check
        uses: workflow/nix-shell-action@main
        continue-on-error: true
        with:
          packages: statix
          script: |
            statix check
      - name: Run statix fix
        uses: workflow/nix-shell-action@main
        with:
          packages: statix
          script: |
            statix fix
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Lint using Statix"
